'use strict';
const KEY='ctu-buddy-project-v1', DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=s=>s.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const safeURL=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}};
const attachmentOK=s=>/^data:(application\/pdf|text\/plain|image\/(png|jpeg|webp));base64,[A-Za-z0-9+/]*={0,2}$/.test(s);
const seed=()=>({version:1,profile:'Ethan Billett',classes:[{id:'c1',day:'Monday',start:'09:00',end:'10:30',subject:'Programming fundamentals',room:'Lab 2'},{id:'c2',day:'Tuesday',start:'11:00',end:'12:30',subject:'Web development',room:'Lab 1'},{id:'c3',day:'Wednesday',start:'09:00',end:'10:30',subject:'Database design',room:'Room 4'},{id:'c4',day:'Thursday',start:'13:00',end:'14:30',subject:'Study group',room:'Library'},{id:'c5',day:'Friday',start:'10:00',end:'11:30',subject:'Project workshop',room:'Lab 2'}],posts:[{id:'p1',title:'How do you plan a programming assignment?',body:'I’m trying to break a big project into smaller steps. What helps you get started?',category:'Programming',author:'Demo student',date:'Sample discussion',liked:false,replies:[{author:'CTU Buddy',body:'Start with the requirements, sketch the screens, then build one feature at a time.'}]},{id:'p2',title:'A study tip that made a difference',body:'Try explaining a topic out loud without looking at your notes. The gaps become much easier to spot.',category:'Study tips',author:'CTU Buddy',date:'Sample discussion',liked:false,replies:[]}],resources:[{id:'r1',title:'HTML quick reference',description:'A small offline reference for page structure, links and images.',author:'CTU Buddy',url:'',fileName:'html-quick-reference.txt',data:'data:text/plain;base64,'+btoa('HTML QUICK REFERENCE\n\n<!doctype html> declares HTML5.\n<html lang="en"> sets the document language.\n<head> contains metadata and stylesheet links.\n<body> contains visible content.\nUse h1 for the main heading; h2 for section headings.\n<a href="page.html"> creates a link.\n<img src="photo.jpg" alt="Description"> displays an image.\n<label for="name"> connects text to an input with id="name".\n'),saved:false},{id:'r2',title:'CSS layout checklist',description:'A practical checklist for responsive pages. Download and keep it handy.',author:'CTU Buddy',url:'',fileName:'css-layout-checklist.txt',data:'data:text/plain;base64,'+btoa('CSS LAYOUT CHECKLIST\n\n[ ] Set box-sizing: border-box.\n[ ] Use flexbox or grid for layouts.\n[ ] Make images responsive with max-width: 100%.\n[ ] Add a viewport meta tag.\n[ ] Test narrow and wide screens.\n[ ] Add visible keyboard focus styles.\n[ ] Check text contrast and readable font sizes.\n[ ] Respect prefers-reduced-motion.\n'),saved:false},{id:'r3',title:'Assignment planning template',description:'Turn a brief into a manageable task list with this simple text template.',author:'CTU Buddy',url:'',fileName:'assignment-planner.txt',data:'data:text/plain;base64,'+btoa('ASSIGNMENT PLANNER\n\nProject:\nDeadline:\n\nRequirements:\n1.\n2.\n3.\n\nTasks and milestones:\n\nQuestions for the lecturer:\n\nTesting checklist:\n\nReferences:\n'),saved:false}],messages:[]});
function validate(d){const str=(v,n)=>typeof v==='string'&&v.length<=n;const arr=(v,n)=>Array.isArray(v)&&v.length<=n;const time=v=>typeof v==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v);const ident=v=>str(v,80)&&/^[a-zA-Z0-9_-]+$/.test(v);if(!d||d.version!==1||!str(d.profile,60)||!d.profile.trim()||!arr(d.classes,200)||!arr(d.posts,200)||!arr(d.resources,100)||!arr(d.messages,200))return false;
if(!d.classes.every(c=>c&&ident(c.id)&&DAYS.includes(c.day)&&time(c.start)&&time(c.end)&&c.end>c.start&&str(c.subject,100)&&str(c.room,80)))return false;
if(!d.posts.every(p=>p&&ident(p.id)&&str(p.title,120)&&str(p.body,2000)&&['General','Programming','Study tips','Campus life'].includes(p.category)&&str(p.author,60)&&str(p.date,80)&&typeof p.liked==='boolean'&&arr(p.replies,100)&&p.replies.every(r=>r&&str(r.author,60)&&str(r.body,1000))))return false;
if(!d.resources.every(r=>r&&ident(r.id)&&str(r.title,120)&&str(r.description,500)&&str(r.author,60)&&str(r.url,2000)&&(!r.url||safeURL(r.url))&&str(r.data,700000)&&(!r.data||attachmentOK(r.data))&&!!(r.url||r.data)&&str(r.fileName,255)&&typeof r.saved==='boolean'))return false;
if(d.resources.reduce((n,r)=>n+r.data.length,0)>2800000)return false;
if(!d.messages.every(m=>m&&ident(m.id)&&str(m.name,80)&&str(m.email,160)&&str(m.message,2000)&&str(m.date,80)))return false;
return ['classes','posts','resources','messages'].every(k=>new Set(d[k].map(x=>x.id)).size===d[k].length);}
let state=seed(),storageAvailable=true;try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(validate(parsed))state=parsed;else storageAvailable=false;}}catch{storageAvailable=false;}
let selectedDay='All',timer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function commit(next){if(!validate(next)){toast('This change exceeds a demo limit or contains invalid data. Export or remove older items first.');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));storageAvailable=true;}catch{toast('Browser storage is unavailable or full. Your previous data is unchanged. Try removing an attachment.');return false;}state=next;render();return true;}
function update(fn){const next=JSON.parse(JSON.stringify(state));fn(next);return commit(next);}
function nextClass(){const now=new Date(),today=(now.getDay()+6)%7,current=now.getHours()*60+now.getMinutes();const classes=state.classes.map(c=>{let delta=(DAYS.indexOf(c.day)-today+7)%7;const [h,m]=c.start.split(':').map(Number);if(delta===0&&h*60+m<=current)delta=7;return {...c,wait:delta*1440+h*60+m-current}}).sort((a,b)=>a.wait-b.wait);return classes[0];}
function render(){const profile=state.profile;$('#greeting').textContent='Hey, '+profile.split(' ')[0]+' 👋';$('#profileButton').textContent=initials(profile);$('#postCount').textContent=state.posts.length;$('#resourceCount').textContent=state.resources.length;$('#classCount').textContent=state.classes.length;const n=nextClass();$('#nextSubject').textContent=n?n.subject:'No classes yet';$('#nextDetails').textContent=n?`${n.day} · ${n.start}–${n.end} · ${n.room}`:'Add your first class below.';
$('#days').innerHTML=['All',...DAYS].map(d=>`<button data-day="${d}" aria-pressed="${d===selectedDay}">${d==='All'?'Full week':d.slice(0,3)}</button>`).join('');const classes=state.classes.filter(c=>selectedDay==='All'||c.day===selectedDay).sort((a,b)=>DAYS.indexOf(a.day)-DAYS.indexOf(b.day)||a.start.localeCompare(b.start));$('#classes').innerHTML=classes.map(c=>`<tr><td>${c.day}</td><td>${c.start}–${c.end}</td><td><strong>${esc(c.subject)}</strong></td><td>${esc(c.room)}</td><td><button class="secondary" data-edit-class="${c.id}">Edit</button> <button class="secondary danger" data-delete-class="${c.id}">Remove</button></td></tr>`).join('')||'<tr><td colspan="5">No classes here yet. Add a class to plan your week.</td></tr>';renderPosts();renderResources();}
function renderPosts(){const q=$('#postSearch').value.toLowerCase(),cat=$('#postFilter').value;const posts=state.posts.filter(p=>(cat==='All topics'||p.category===cat)&&`${p.title} ${p.body} ${p.author}`.toLowerCase().includes(q));$('#posts').innerHTML=posts.map(p=>`<article class="card"><div class="card-top"><span class="pill">${esc(p.category)}</span><button class="secondary danger" data-delete-post="${p.id}" aria-label="Delete discussion: ${esc(p.title)}">×</button></div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.author)} · ${esc(p.date)}</div><p>${esc(p.body)}</p><div class="card-actions"><button class="secondary" aria-pressed="${p.liked}" data-like="${p.id}">${p.liked?'♥ Liked':'♡ Like'}</button></div><details class="replies"><summary>${p.replies.length} ${p.replies.length===1?'reply':'replies'} · Join the conversation</summary>${p.replies.map(r=>`<div class="reply"><strong class="small">${esc(r.author)}</strong><p>${esc(r.body)}</p></div>`).join('')}<form data-reply="${p.id}"><label>Your reply<textarea name="reply" required maxlength="1000" rows="2"></textarea></label><button>Reply locally</button></form></details></article>`).join('')||'<p class="empty">No discussions match. Start a conversation or change your search.</p>';}
function renderResources(){const q=$('#resourceSearch').value.toLowerCase(),saved=$('#savedOnly').checked;$('#resourcesList').innerHTML=state.resources.filter(r=>(!saved||r.saved)&&`${r.title} ${r.description}`.toLowerCase().includes(q)).map(r=>`<article class="card"><div class="card-top"><span class="resource-icon">${r.data?'↓':'↗'}</span><button class="secondary danger" data-delete-resource="${r.id}" aria-label="Delete resource: ${esc(r.title)}">×</button></div><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><div class="meta">Shared by ${esc(r.author)}</div><div class="card-actions">${r.data?`<button data-download="${r.id}">Download</button>`:`<a class="button" href="${esc(safeURL(r.url))}" target="_blank" rel="noopener noreferrer">Open link ↗</a>`}<button class="secondary bookmark" data-save="${r.id}" aria-pressed="${r.saved}">${r.saved?'★ Saved':'☆ Save'}</button></div></article>`).join('')||'<p class="empty">No resources found. Add one or change your filters.</p>';}
function finish(form,message){form.closest('dialog')?.close();form.reset();toast(message);}
function fields(form){return Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,typeof v==='string'?v.trim():v]));}
function requiredText(form){for(const el of form.querySelectorAll('input[required],textarea[required]')){if(!el.value.trim()){el.setCustomValidity('Please enter some text.');el.reportValidity();return false;}}return true;}
document.addEventListener('input',e=>{if(e.target.setCustomValidity)e.target.setCustomValidity('');});
$('#menu').onclick=()=>{const open=$('#navlinks').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open);};$('#navlinks').onclick=e=>{if(e.target.closest('a')){$('#navlinks').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#navlinks').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');}});
$$('[data-open]').forEach(b=>b.onclick=()=>{const d=$('#'+b.dataset.open);d.querySelector('form').reset();if(d.id==='classDialog'){delete $('#classForm').dataset.edit;d.querySelector('h2').textContent='Add a class';}d.showModal();});$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#profileButton').onclick=()=>{$('#profileForm').elements.name.value=state.profile;$('#profileDialog').showModal();};$('#profileForm').onsubmit=e=>{e.preventDefault();if(!requiredText(e.target))return;const v=fields(e.target);if(update(d=>d.profile=v.name))finish(e.target,'Profile updated.');};
$('#days').onclick=e=>{const b=e.target.closest('[data-day]');if(b){selectedDay=b.dataset.day;render();}};
$('#classForm').onsubmit=e=>{e.preventDefault();const f=e.target;if(!requiredText(f))return;const v=fields(f);if(v.end<=v.start){f.elements.end.setCustomValidity('End time must be after the start time.');f.elements.end.reportValidity();return;}const id=f.dataset.edit||uid();if(state.classes.some(c=>c.id!==id&&c.day===v.day&&v.start<c.end&&v.end>c.start)){toast('This class overlaps another class on '+v.day+'. Choose a different time.');return;}if(update(d=>{const c={...v,id};const i=d.classes.findIndex(x=>x.id===id);if(i<0)d.classes.push(c);else d.classes[i]=c;}))finish(f,'Timetable updated.');};
$('#classes').onclick=e=>{const edit=e.target.closest('[data-edit-class]'),del=e.target.closest('[data-delete-class]');if(edit){const c=state.classes.find(x=>x.id===edit.dataset.editClass),f=$('#classForm');for(const k of ['subject','day','start','end','room'])f.elements[k].value=c[k];f.dataset.edit=c.id;$('#classDialog h2').textContent='Edit class';$('#classDialog').showModal();}if(del&&confirm('Remove this class?'))update(d=>d.classes=d.classes.filter(x=>x.id!==del.dataset.deleteClass));};
$('#printWeek').onclick=()=>{selectedDay='All';render();window.print();};
$('#postForm').onsubmit=e=>{e.preventDefault();if(!requiredText(e.target))return;const v=fields(e.target);if(update(d=>d.posts.unshift({...v,id:uid(),author:d.profile,date:new Date().toLocaleDateString(),liked:false,replies:[]}))){$('#postSearch').value='';$('#postFilter').value='All topics';renderPosts();finish(e.target,'Discussion saved locally.');}};
$('#postSearch').oninput=renderPosts;$('#postFilter').onchange=renderPosts;
$('#posts').onclick=e=>{const like=e.target.closest('[data-like]'),del=e.target.closest('[data-delete-post]');if(like)update(d=>{const p=d.posts.find(x=>x.id===like.dataset.like);p.liked=!p.liked;});if(del&&confirm('Delete this discussion and its replies?'))update(d=>d.posts=d.posts.filter(p=>p.id!==del.dataset.deletePost));};
$('#posts').onsubmit=e=>{const f=e.target.closest('[data-reply]');if(!f)return;e.preventDefault();if(!requiredText(f))return;const id=f.dataset.reply,body=fields(f).reply;if(update(d=>d.posts.find(p=>p.id===id).replies.push({author:d.profile,body}))){const replacement=$(`[data-reply="${id}"]`);replacement.closest('details').open=true;replacement.elements.reply.focus();toast('Reply added locally.');}};
const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read the file.'));r.readAsDataURL(file);});
$('#resourceForm').onsubmit=async e=>{e.preventDefault();const f=e.target;if(!requiredText(f))return;const v=fields(f),file=f.elements.file.files[0];if((file&&v.url)||(!file&&!v.url)){toast('Choose either a website link or one file.');return;}let data='',fileName='';if(v.url&&!safeURL(v.url)){toast('Use an http:// or https:// link.');return;}const button=f.querySelector('button:not([type])');button.disabled=true;try{if(file){const types={pdf:'application/pdf',txt:'text/plain',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp'},ext=file.name.split('.').pop().toLowerCase();if(!types[ext]||file.size>500*1024)throw Error('Choose a PDF, text file or image up to 500 KB.');data=await readFile(file);data='data:'+types[ext]+';base64,'+data.split(',')[1];fileName=file.name;}if(update(d=>d.resources.unshift({id:uid(),title:v.title,description:v.description,url:v.url? safeURL(v.url):'',data,fileName,author:d.profile,saved:false}))){$('#resourceSearch').value='';$('#savedOnly').checked=false;renderResources();finish(f,'Resource saved locally.');}}catch(err){toast(err.message);}finally{button.disabled=false;}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#resourceSearch').oninput=renderResources;$('#savedOnly').onchange=renderResources;
$('#resourcesList').onclick=e=>{const saved=e.target.closest('[data-save]'),del=e.target.closest('[data-delete-resource]'),dl=e.target.closest('[data-download]');if(saved)update(d=>{const r=d.resources.find(x=>x.id===saved.dataset.save);r.saved=!r.saved;});if(del&&confirm('Delete this resource?'))update(d=>d.resources=d.resources.filter(r=>r.id!==del.dataset.deleteResource));if(dl){const r=state.resources.find(x=>x.id===dl.dataset.download);const [head,body]=r.data.split(',');download(new Blob([Uint8Array.from(atob(body),c=>c.charCodeAt(0))],{type:head.slice(5).split(';')[0]}),r.fileName);}};
$('#contactForm').onsubmit=e=>{e.preventDefault();if(!requiredText(e.target))return;const v=fields(e.target);if(update(d=>d.messages.unshift({...v,id:uid(),date:new Date().toLocaleString()}))){e.target.reset();$('#contactStatus').textContent='Enquiry saved in this browser. No message was sent.';toast('Enquiry saved locally.');}};
function renderMessages(){$('#messages').innerHTML=state.messages.map(m=>`<article class="card"><strong>${esc(m.name)}</strong><div class="meta">${esc(m.email)} · ${esc(m.date)}</div><p>${esc(m.message)}</p><button class="secondary danger" data-delete-message="${m.id}">Delete</button></article>`).join('')||'<p class="muted">No enquiries saved yet.</p>';}
$('#viewMessages').onclick=()=>{renderMessages();$('#messagesDialog').showModal();};$('#messages').onclick=e=>{const b=e.target.closest('[data-delete-message]');if(b&&confirm('Delete this enquiry?')){update(d=>d.messages=d.messages.filter(m=>m.id!==b.dataset.deleteMessage));renderMessages();}};
$('#exportData').onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'ctu-buddy-backup.json');
$('#importData').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>4*1024*1024)throw Error('Backup is too large.');const data=JSON.parse(await file.text());if(!validate(data))throw Error('This is not a valid CTU Buddy backup.');if(confirm('Replace your current local data with this backup?')&&commit(data))toast('Backup restored.');}catch(err){toast(err.message);}finally{e.target.value='';}};
$('#resetData').onclick=()=>{if(confirm('Reset all local posts, resources, classes, profile and enquiries? Export a backup first if you want to keep them.')){selectedDay='All';$('#postSearch').value='';$('#postFilter').value='All topics';$('#resourceSearch').value='';$('#savedOnly').checked=false;if(commit(seed()))toast('Sample content restored.');}};
$('#year').textContent=new Date().getFullYear();render();if(!storageAvailable)toast('Saved data could not be loaded. Export a backup before making changes.');
